import React, { useMemo, useEffect } from 'react';
import * as THREE from 'three';
import { createAsphaltTexture } from './assets/proceduralTextures';
import { setCurve } from './trackUtils';

export function Track({ radius = 80, laneWidth = 5.5 }) {
  // build a smooth closed CatmullRom curve with slight variation for corners
  const points = useMemo(() => {
    const pts = [];
    const n = 64;
    for (let i = 0; i < n; i++) {
      const a = (i / n) * Math.PI * 2;
      const r = radius + Math.sin(a * 3) * 10 + Math.cos(a * 2) * 6;
      const x = Math.cos(a) * r;
      const z = Math.sin(a) * (radius * 0.9 + Math.sin(a * 2) * 6);
      const y = Math.sin(a * 4) * 0.6;
      pts.push(new THREE.Vector3(x, y, z));
    }

    // ensure first ~20m is straight by prepending points along the tangent
    const p0 = pts[0].clone();
    const p1 = pts[1].clone();
    const dir = p1.clone().sub(p0).normalize();
    pts.unshift(p0.clone().sub(dir.clone().multiplyScalar(40)), p0.clone().sub(dir.clone().multiplyScalar(20)));

    return pts;
  }, [radius]);

  useEffect(() => {
    const curve = new THREE.CatmullRomCurve3(points, true, 'centripetal');
    setCurve(curve, 1024);
  }, [points]);

  const curve = useMemo(() => new THREE.CatmullRomCurve3(points, true, 'centripetal'), [points]);

  const asphaltTex = useMemo(() => createAsphaltTexture(1024), []);
  const bumpTex = useMemo(() => createAsphaltTexture(512), []);

  // guardrail paths (left/right) generated by offsetting curve points along local normal
  const leftCurve = useMemo(() => {
    const pts = curve.getPoints(512).map((p, i, arr) => {
      const t = i / (arr.length - 1);
      const tangent = curve.getTangent(t).normalize();
      const normal = new THREE.Vector3().crossVectors(new THREE.Vector3(0, 1, 0), tangent).normalize();
      return p.clone().add(normal.multiplyScalar((laneWidth / 2) + 0.5));
    });
    return new THREE.CatmullRomCurve3(pts, true, 'centripetal');
  }, [curve, laneWidth]);

  const rightCurve = useMemo(() => {
    const pts = curve.getPoints(512).map((p, i, arr) => {
      const t = i / (arr.length - 1);
      const tangent = curve.getTangent(t).normalize();
      const normal = new THREE.Vector3().crossVectors(new THREE.Vector3(0, 1, 0), tangent).normalize();
      return p.clone().add(normal.multiplyScalar(-(laneWidth / 2) - 0.5));
    });
    return new THREE.CatmullRomCurve3(pts, true, 'centripetal');
  }, [curve, laneWidth]);

  return (
    <group>
      <mesh rotation={[-Math.PI / 2, 0, 0]}>
        <tubeGeometry args={[curve, 1024, laneWidth, 8, true]} />
        <meshStandardMaterial
          map={asphaltTex}
          color={0xffffff}
          metalness={0.03}
          roughness={0.85}
          bumpMap={bumpTex}
          bumpScale={0.02}
        />
      </mesh>

      <mesh>
        <tubeGeometry args={[leftCurve, 512, 0.12, 6, true]} />
        <meshStandardMaterial color="#777" metalness={0.8} roughness={0.4} />
      </mesh>

      <mesh>
        <tubeGeometry args={[rightCurve, 512, 0.12, 6, true]} />
        <meshStandardMaterial color="#777" metalness={0.8} roughness={0.4} />
      </mesh>
    </group>
  );
}
